### ISSUE TITLE
How to write CLI commands to eeprom

### ISSUE THREAD

**Issue by weixingsun** [christianrauch/msp#25]
It's so good to see the codes to read data from fc.
It would be nice to have a way to write data (to eeprom) instead of the xxflight configurator
Because I want to set multiple options in a time, like:
set serial_update_rate_hz=1000
feature RX_MSP
map AERT1234
...
maybe more in future, so it'll be convenient to have a script to do this without bothering it manually
thanks

**Comment by christianrauch** [comment]
You can access some of the options via MSP messages. E.g. you can set the features via `MSP_SET_FEATURE` and store them permanently in the EEPROM via `MSP_EEPROM_WRITE`.

However, I am not aware of a general CLI access via a MSP message. I guess it could easily be enables by a simple string message request and response.
You could add a feature request for this in the betaflight issue tracker.

**Comment by christianrauch** [comment]
@weixingsun Have you found a MSP message that allows to configure the FC (as a replacement for the CLI)?
