### ISSUE TITLE
asio.hpp not found

### ISSUE THREAD

**Issue by fernandorocha** [christianrauch/msp#4]
I was trying to build the msp library today but compilation failed for not finding asio.hpp.
I have libboost installed correctly, there is a /usr/include/boost/asio.h, but the build system couldn't find it.

I checked the previous commit and it worked fine.

**Comment by christianrauch** [comment]
I recently switched to the standalone header-only version of asio (https://think-async.com) to remove the dependency on boost:
`sudo apt install --no-install-recommends libasio-dev`

**Comment by fernandorocha** [comment]
After installing libasio-dev, it compiles OK. Thanks
