### ISSUE TITLE
No executables after cmake

### ISSUE THREAD

**Issue by Anderson321** [christianrauch/msp#5]
Hi after I ran cmake in the msp directory it says "build files have been written to /home/pi/msp" but when i go into the examples directory i can't run ./msp_read_test 

cmake is supposed to make this and link the headers right?

Thanks

**Comment by christianrauch** [comment]
I forgot to mention, that you need to call `make` at the end. This is actually compiling the libraries and executables. Ideally, you would call cmake from a different directory, e.g. `build`, to separate source and compilation.
E.g. change to `/home/pi/msp` and run:
`mkdir build && cd build && cmake ..&& make -j`
This will place the executable at `/home/pi/msp/build/msp_read_test`.
